import os

scss = (
    "// ==========================================\n"
    "// DASHBOARD PAGE\n"
    "// ==========================================\n"
    "\n"
    ".page-container {\n"
    "  max-width: 1280px;\n"
    "  margin: 0 auto;\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  gap: 24px;\n"
    "}\n"
    "\n"
    "// WELCOME HERO\n"
    ".welcome-hero {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  justify-content: space-between;\n"
    "  gap: 20px;\n"
    "  background: linear-gradient(135deg, var(--gov-primary-dark) 0%, var(--gov-primary) 100%);\n"
    "  border-radius: 16px;\n"
    "  padding: 24px 28px;\n"
    "  flex-wrap: wrap;\n"
    "}\n"
    "\n"
    ".welcome-hero-left {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  gap: 18px;\n"
    "}\n"
    "\n"
    ".welcome-avatar {\n"
    "  width: 56px;\n"
    "  height: 56px;\n"
    "  border-radius: 50%;\n"
    "  background: rgba(255, 255, 255, 0.22);\n"
    "  border: 2px solid rgba(255, 255, 255, 0.45);\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  justify-content: center;\n"
    "  font-size: 1.25rem;\n"
    "  font-weight: 700;\n"
    "  color: #fff;\n"
    "  text-transform: uppercase;\n"
    "  flex-shrink: 0;\n"
    "  letter-spacing: 0.5px;\n"
    "}\n"
    "\n"
    ".greeting-text {\n"
    "  font-size: 0.92rem;\n"
    "  color: rgba(255, 255, 255, 0.85);\n"
    "  margin: 0 0 4px;\n"
    "  strong { font-weight: 700; color: #fff; }\n"
    "}\n"
    "\n"
    ".page-title {\n"
    "  font-size: 1.45rem;\n"
    "  font-weight: 700;\n"
    "  color: #fff;\n"
    "  margin: 0 0 6px;\n"
    "  font-family: 'Raleway', sans-serif;\n"
    "}\n"
    "\n"
    ".page-date {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  gap: 4px;\n"
    "  font-size: 0.8rem;\n"
    "  color: rgba(255, 255, 255, 0.65);\n"
    "  margin: 0;\n"
    "  text-transform: capitalize;\n"
    "  .date-icon { font-size: 14px; width: 14px; height: 14px; }\n"
    "}\n"
    "\n"
    ".manage-btn {\n"
    "  flex-shrink: 0;\n"
    "  background: rgba(255, 255, 255, 0.18) !important;\n"
    "  color: #fff !important;\n"
    "  border: 1.5px solid rgba(255, 255, 255, 0.35) !important;\n"
    "  border-radius: 10px !important;\n"
    "  &:hover { background: rgba(255, 255, 255, 0.28) !important; }\n"
    "  mat-icon { margin-right: 6px; }\n"
    "}\n"
    "\n"
    "// SKELETON\n"
    "@keyframes shimmer {\n"
    "  0%   { background-position: -600px 0; }\n"
    "  100% { background-position: 600px 0; }\n"
    "}\n"
    "\n"
    ".skeleton {\n"
    "  border-radius: 12px;\n"
    "  background: linear-gradient(90deg, #e2e8f0 25%, #edf2f7 50%, #e2e8f0 75%);\n"
    "  background-size: 1200px 100%;\n"
    "  animation: shimmer 1.4s ease-in-out infinite;\n"
    "}\n"
    "\n"
    ".skeleton-section { display: flex; flex-direction: column; gap: 20px; }\n"
    ".sk-banner { height: 88px; }\n"
    "\n"
    ".stats-grid {\n"
    "  display: grid;\n"
    "  grid-template-columns: repeat(4, 1fr);\n"
    "  gap: 16px;\n"
    "}\n"
    "\n"
    ".sk-card { height: 130px; }\n"
    ".sk-body { height: 360px; }\n"
    "\n"
    "// ERROR STATE\n"
    ".error-state {\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  align-items: center;\n"
    "  gap: 10px;\n"
    "  padding: 56px 24px;\n"
    "  text-align: center;\n"
    "  h3 { font-size: 1.1rem; font-weight: 600; color: var(--gov-text); margin: 0; }\n"
    "  p  { font-size: 0.9rem; color: var(--gov-text-secondary); margin: 0; }\n"
    "}\n"
    "\n"
    ".error-icon-wrap {\n"
    "  width: 60px; height: 60px;\n"
    "  border-radius: 50%;\n"
    "  background: #fef2f2;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  mat-icon { font-size: 28px; width: 28px; height: 28px; color: #ef4444; }\n"
    "}\n"
    "\n"
    "// TOTAL BANNER\n"
    ".total-banner {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  gap: 16px;\n"
    "  background: var(--gov-surface);\n"
    "  border-radius: 14px;\n"
    "  padding: 18px 24px;\n"
    "  border: 1px solid var(--gov-border);\n"
    "  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.04);\n"
    "  flex-wrap: wrap;\n"
    "}\n"
    "\n"
    ".banner-icon-wrap {\n"
    "  width: 52px; height: 52px;\n"
    "  border-radius: 12px;\n"
    "  background: var(--gov-primary);\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  flex-shrink: 0;\n"
    "  mat-icon { font-size: 26px; width: 26px; height: 26px; color: #fff; }\n"
    "}\n"
    "\n"
    ".banner-text {\n"
    "  flex: 1;\n"
    "  display: flex;\n"
    "  align-items: baseline;\n"
    "  gap: 10px;\n"
    "  flex-wrap: wrap;\n"
    "}\n"
    "\n"
    ".banner-number {\n"
    "  font-size: 2.2rem;\n"
    "  font-weight: 800;\n"
    "  color: var(--gov-primary);\n"
    "  line-height: 1;\n"
    "  font-family: 'Raleway', sans-serif;\n"
    "}\n"
    "\n"
    ".banner-label { font-size: 0.9rem; color: var(--gov-text-secondary); }\n"
    "\n"
    ".banner-cta {\n"
    "  flex-shrink: 0;\n"
    "  color: var(--gov-primary) !important;\n"
    "  border-color: var(--gov-primary) !important;\n"
    "  border-radius: 8px !important;\n"
    "  mat-icon { margin-left: 4px; }\n"
    "}\n"
    "\n"
    "// KPI CARDS\n"
    ".stat-card {\n"
    "  background: var(--gov-surface);\n"
    "  border-radius: 14px;\n"
    "  padding: 18px;\n"
    "  border: 1px solid var(--gov-border);\n"
    "  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.04);\n"
    "  transition: transform 0.15s, box-shadow 0.15s;\n"
    "  &:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0, 0, 0, 0.09); }\n"
    "}\n"
    "\n"
    ".stat-card-head {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  justify-content: space-between;\n"
    "  margin-bottom: 14px;\n"
    "}\n"
    "\n"
    ".stat-icon {\n"
    "  width: 42px; height: 42px;\n"
    "  border-radius: 10px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  flex-shrink: 0;\n"
    "  mat-icon { font-size: 22px; width: 22px; height: 22px; }\n"
    "}\n"
    "\n"
    ".stat-trend {\n"
    "  font-size: 0.78rem;\n"
    "  font-weight: 700;\n"
    "  border-radius: 20px;\n"
    "  padding: 3px 8px;\n"
    "}\n"
    "\n"
    ".stat-value {\n"
    "  font-size: 2rem;\n"
    "  font-weight: 800;\n"
    "  color: var(--gov-text);\n"
    "  line-height: 1;\n"
    "  margin-bottom: 4px;\n"
    "  font-family: 'Raleway', sans-serif;\n"
    "}\n"
    "\n"
    ".stat-label { font-size: 0.8rem; color: var(--gov-text-secondary); margin-bottom: 12px; }\n"
    "\n"
    ".stat-bar {\n"
    "  height: 4px;\n"
    "  border-radius: 4px;\n"
    "  background: var(--gov-border);\n"
    "  overflow: hidden;\n"
    "}\n"
    "\n"
    ".stat-bar-fill {\n"
    "  height: 100%;\n"
    "  border-radius: 4px;\n"
    "  transition: width 0.6s ease;\n"
    "}\n"
    "\n"
    "// CONTENT GRID\n"
    ".content-grid {\n"
    "  display: grid;\n"
    "  grid-template-columns: 1fr 1.4fr;\n"
    "  gap: 20px;\n"
    "  align-items: start;\n"
    "}\n"
    "\n"
    "// PANEL CARD\n"
    ".panel-card {\n"
    "  border-radius: 14px !important;\n"
    "  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05) !important;\n"
    "  border: 1px solid var(--gov-border) !important;\n"
    "\n"
    "  mat-card-header {\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: space-between;\n"
    "    padding: 18px 20px 12px;\n"
    "    gap: 12px;\n"
    "  }\n"
    "\n"
    "  mat-card-content {\n"
    "    padding: 0 20px 20px;\n"
    "  }\n"
    "}\n"
    "\n"
    ".panel-title {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  gap: 8px;\n"
    "  font-size: 0.95rem;\n"
    "  font-weight: 700;\n"
    "  color: var(--gov-text);\n"
    "  mat-icon { font-size: 20px; width: 20px; height: 20px; color: var(--gov-primary); }\n"
    "}\n"
    "\n"
    ".panel-link-btn {\n"
    "  flex-shrink: 0;\n"
    "  font-size: 0.8rem !important;\n"
    "  color: var(--gov-primary) !important;\n"
    "  border-color: var(--gov-border) !important;\n"
    "  border-radius: 8px !important;\n"
    "  height: 32px !important;\n"
    "  line-height: 30px !important;\n"
    "  mat-icon { font-size: 16px; width: 16px; height: 16px; }\n"
    "}\n"
    "\n"
    "// CATEGORY LIST\n"
    ".cat-list { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 14px; }\n"
    "\n"
    ".cat-row { display: flex; align-items: center; gap: 12px; }\n"
    "\n"
    ".cat-icon-wrap {\n"
    "  width: 36px; height: 36px;\n"
    "  border-radius: 8px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  flex-shrink: 0;\n"
    "  mat-icon { font-size: 18px; width: 18px; height: 18px; }\n"
    "}\n"
    "\n"
    ".cat-info { flex: 1; min-width: 0; }\n"
    "\n"
    ".cat-meta {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  justify-content: space-between;\n"
    "  margin-bottom: 5px;\n"
    "}\n"
    "\n"
    ".cat-name {\n"
    "  font-size: 0.85rem;\n"
    "  font-weight: 500;\n"
    "  color: var(--gov-text);\n"
    "  white-space: nowrap;\n"
    "  overflow: hidden;\n"
    "  text-overflow: ellipsis;\n"
    "}\n"
    "\n"
    ".cat-count {\n"
    "  display: flex; align-items: center; gap: 4px; flex-shrink: 0;\n"
    "  strong { font-size: 0.88rem; font-weight: 700; color: var(--gov-text); }\n"
    "}\n"
    "\n"
    ".cat-pct { font-size: 0.75rem; color: var(--gov-text-muted); }\n"
    "\n"
    ".cat-bar-track {\n"
    "  height: 5px; border-radius: 5px;\n"
    "  background: var(--gov-border);\n"
    "  overflow: hidden;\n"
    "}\n"
    "\n"
    ".cat-bar-fill {\n"
    "  height: 100%;\n"
    "  border-radius: 5px;\n"
    "  transition: width 0.6s ease;\n"
    "  min-width: 4px;\n"
    "}\n"
    "\n"
    "// REPORTS TABLE\n"
    ".table-scroll { overflow-x: auto; }\n"
    "\n"
    ".reports-table {\n"
    "  width: 100%;\n"
    "\n"
    "  th {\n"
    "    font-size: 0.78rem;\n"
    "    font-weight: 700;\n"
    "    color: var(--gov-text-secondary);\n"
    "    text-transform: uppercase;\n"
    "    letter-spacing: 0.4px;\n"
    "    background: var(--gov-bg);\n"
    "  }\n"
    "\n"
    "  td {\n"
    "    font-size: 0.85rem;\n"
    "    color: var(--gov-text);\n"
    "    padding: 10px 12px !important;\n"
    "    border-bottom: 1px solid var(--gov-border);\n"
    "    white-space: nowrap;\n"
    "  }\n"
    "}\n"
    "\n"
    ".clickable-row {\n"
    "  cursor: pointer;\n"
    "  transition: background 0.12s;\n"
    "  &:hover td { background: var(--gov-bg); }\n"
    "  &:focus-visible { outline: 2px solid var(--gov-primary); outline-offset: -2px; }\n"
    "}\n"
    "\n"
    ".report-title-cell {\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  gap: 2px;\n"
    "  max-width: 240px;\n"
    "}\n"
    "\n"
    ".report-title {\n"
    "  font-weight: 600;\n"
    "  white-space: nowrap;\n"
    "  overflow: hidden;\n"
    "  text-overflow: ellipsis;\n"
    "}\n"
    "\n"
    ".report-citizen {\n"
    "  display: flex; align-items: center; gap: 2px;\n"
    "  font-size: 0.75rem; color: var(--gov-text-muted);\n"
    "  mat-icon { font-size: 12px; width: 12px; height: 12px; }\n"
    "}\n"
    "\n"
    ".category-cell { font-size: 0.82rem; color: var(--gov-text-secondary); }\n"
    ".date-cell { font-size: 0.8rem; color: var(--gov-text-muted); }\n"
    "\n"
    "// STATUS CHIP\n"
    ".status-chip {\n"
    "  display: inline-block;\n"
    "  padding: 3px 10px;\n"
    "  border-radius: 20px;\n"
    "  font-size: 0.75rem;\n"
    "  font-weight: 600;\n"
    "  text-transform: uppercase;\n"
    "  letter-spacing: 0.3px;\n"
    "\n"
    "  &[data-status='PENDING']     { background: var(--status-pending-bg);   color: var(--status-pending-text); }\n"
    "  &[data-status='IN_PROGRESS'] { background: #eff6ff;                   color: #1d4ed8; }\n"
    "  &[data-status='RESOLVED']    { background: var(--status-resolved-bg);  color: var(--status-resolved-text); }\n"
    "  &[data-status='REJECTED']    { background: var(--status-rejected-bg);  color: var(--status-rejected-text); }\n"
    "}\n"
    "\n"
    "// EMPTY STATE\n"
    ".empty-panel {\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  align-items: center;\n"
    "  gap: 8px;\n"
    "  padding: 36px 16px;\n"
    "  color: var(--gov-text-muted);\n"
    "  mat-icon { font-size: 36px; width: 36px; height: 36px; opacity: 0.45; }\n"
    "  p { font-size: 0.88rem; margin: 0; }\n"
    "}\n"
    "\n"
    "// RESPONSIVE\n"
    "@media (max-width: 1100px) {\n"
    "  .stats-grid { grid-template-columns: repeat(2, 1fr); }\n"
    "  .content-grid { grid-template-columns: 1fr; }\n"
    "}\n"
    "\n"
    "@media (max-width: 640px) {\n"
    "  .welcome-hero { padding: 18px 16px; flex-direction: column; align-items: flex-start; }\n"
    "  .manage-btn { width: 100%; justify-content: center; }\n"
    "  .stats-grid { grid-template-columns: repeat(2, 1fr); gap: 12px; }\n"
    "  .banner-number { font-size: 1.8rem; }\n"
    "  .stat-value { font-size: 1.6rem; }\n"
    "  .total-banner { padding: 14px 16px; }\n"
    "}\n"
)

path = r"c:\Users\jose\Desktop\PROYECTOS GIT\Echarati-road-reports\src\app\features\admin\pages\dashboard\dashboard-page.component.scss"
with open(path, "w", encoding="utf-8") as f:
    f.write(scss)
print("OK")
