import os

scss = (
    "// ==========================================\n"
    "// DASHBOARD PAGE\n"
    "// ==========================================\n"
    "\n"
    ".page-container {\n"
    "  max-width: 1260px;\n"
    "  margin: 0 auto;\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  gap: 22px;\n"
    "}\n"
    "\n"
    "// WELCOME HERO\n"
    ".welcome-hero {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  justify-content: space-between;\n"
    "  gap: 20px;\n"
    "  background: linear-gradient(135deg, var(--gov-primary-dark) 0%, var(--gov-primary) 100%);\n"
    "  border-radius: 14px;\n"
    "  padding: 22px 28px;\n"
    "  flex-wrap: wrap;\n"
    "}\n"
    "\n"
    ".welcome-hero-left {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  gap: 16px;\n"
    "}\n"
    "\n"
    ".welcome-avatar {\n"
    "  width: 52px;\n"
    "  height: 52px;\n"
    "  border-radius: 50%;\n"
    "  background: rgba(255, 255, 255, 0.22);\n"
    "  border: 2px solid rgba(255, 255, 255, 0.4);\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  justify-content: center;\n"
    "  font-size: 1.2rem;\n"
    "  font-weight: 700;\n"
    "  color: #fff;\n"
    "  text-transform: uppercase;\n"
    "  flex-shrink: 0;\n"
    "}\n"
    "\n"
    ".greeting-text {\n"
    "  font-size: 0.88rem;\n"
    "  color: rgba(255, 255, 255, 0.8);\n"
    "  margin: 0 0 3px;\n"
    "  strong { color: #fff; font-weight: 700; }\n"
    "}\n"
    "\n"
    ".page-title {\n"
    "  font-size: 1.4rem;\n"
    "  font-weight: 700;\n"
    "  color: #fff;\n"
    "  margin: 0 0 4px;\n"
    "  font-family: 'Raleway', sans-serif;\n"
    "}\n"
    "\n"
    ".page-date {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  gap: 4px;\n"
    "  font-size: 0.78rem;\n"
    "  color: rgba(255, 255, 255, 0.6);\n"
    "  margin: 0;\n"
    "  text-transform: capitalize;\n"
    "  .date-icon { font-size: 13px; width: 13px; height: 13px; }\n"
    "}\n"
    "\n"
    ".manage-btn {\n"
    "  flex-shrink: 0;\n"
    "  background: rgba(255, 255, 255, 0.16) !important;\n"
    "  color: #fff !important;\n"
    "  border: 1.5px solid rgba(255, 255, 255, 0.32) !important;\n"
    "  border-radius: 10px !important;\n"
    "  &:hover { background: rgba(255, 255, 255, 0.26) !important; }\n"
    "  mat-icon { margin-right: 6px; }\n"
    "}\n"
    "\n"
    "// ==========================================\n"
    "// SKELETON\n"
    "// ==========================================\n"
    "@keyframes shimmer {\n"
    "  0%   { background-position: -600px 0; }\n"
    "  100% { background-position: 600px 0; }\n"
    "}\n"
    "\n"
    ".skeleton {\n"
    "  border-radius: 12px;\n"
    "  background: linear-gradient(90deg, #e2e8f0 25%, #edf2f7 50%, #e2e8f0 75%);\n"
    "  background-size: 1200px 100%;\n"
    "  animation: shimmer 1.4s ease-in-out infinite;\n"
    "}\n"
    "\n"
    ".skeleton-section {\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  gap: 20px;\n"
    "}\n"
    "\n"
    ".skeleton-card {\n"
    "  background: var(--gov-surface);\n"
    "  border-radius: 14px;\n"
    "  border: 1px solid var(--gov-border);\n"
    "  padding: 28px 32px;\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  gap: 20px;\n"
    "}\n"
    "\n"
    ".sk-rings-row {\n"
    "  display: flex;\n"
    "  gap: 32px;\n"
    "}\n"
    "\n"
    ".sk-ring {\n"
    "  width: 120px;\n"
    "  height: 120px;\n"
    "  border-radius: 50%;\n"
    "  flex-shrink: 0;\n"
    "}\n"
    "\n"
    ".sk-chart {\n"
    "  height: 120px;\n"
    "}\n"
    "\n"
    ".sk-table {\n"
    "  height: 260px;\n"
    "}\n"
    "\n"
    "// ==========================================\n"
    "// ERROR STATE\n"
    "// ==========================================\n"
    ".error-state {\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  align-items: center;\n"
    "  gap: 10px;\n"
    "  padding: 56px 24px;\n"
    "  text-align: center;\n"
    "  h3 { font-size: 1.1rem; font-weight: 600; color: var(--gov-text); margin: 0; }\n"
    "  p  { font-size: 0.9rem; color: var(--gov-text-secondary); margin: 0; }\n"
    "}\n"
    "\n"
    ".error-icon-wrap {\n"
    "  width: 60px; height: 60px;\n"
    "  border-radius: 50%;\n"
    "  background: #fef2f2;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  mat-icon { font-size: 28px; width: 28px; height: 28px; color: #ef4444; }\n"
    "}\n"
    "\n"
    "// ==========================================\n"
    "// OVERVIEW CARD\n"
    "// ==========================================\n"
    ".overview-card {\n"
    "  background: var(--gov-surface);\n"
    "  border-radius: 14px;\n"
    "  border: 1px solid var(--gov-border);\n"
    "  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);\n"
    "  overflow: hidden;\n"
    "}\n"
    "\n"
    ".overview-body {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  gap: 0;\n"
    "  padding: 28px 32px;\n"
    "}\n"
    "\n"
    ".overview-vdivider {\n"
    "  width: 1px;\n"
    "  align-self: stretch;\n"
    "  background: var(--gov-border);\n"
    "  margin: 0 32px;\n"
    "  flex-shrink: 0;\n"
    "}\n"
    "\n"
    ".overview-footer {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  gap: 8px;\n"
    "  padding: 12px 32px;\n"
    "  background: var(--gov-bg);\n"
    "\n"
    "  mat-icon {\n"
    "    font-size: 16px;\n"
    "    width: 16px;\n"
    "    height: 16px;\n"
    "    color: var(--gov-text-muted);\n"
    "  }\n"
    "}\n"
    "\n"
    ".overview-total-text {\n"
    "  font-size: 0.8rem;\n"
    "  color: var(--gov-text-secondary);\n"
    "  text-transform: uppercase;\n"
    "  letter-spacing: 0.3px;\n"
    "\n"
    "  strong {\n"
    "    color: var(--gov-primary);\n"
    "    font-size: 0.9rem;\n"
    "  }\n"
    "}\n"
    "\n"
    ".footer-spacer { flex: 1; }\n"
    "\n"
    ".overview-cta {\n"
    "  flex-shrink: 0;\n"
    "  font-size: 0.8rem !important;\n"
    "  color: var(--gov-primary) !important;\n"
    "  border-color: var(--gov-border) !important;\n"
    "  border-radius: 8px !important;\n"
    "  height: 32px !important;\n"
    "  line-height: 30px !important;\n"
    "}\n"
    "\n"
    "// ==========================================\n"
    "// RING KPIs\n"
    "// ==========================================\n"
    ".rings-area {\n"
    "  display: flex;\n"
    "  gap: 28px;\n"
    "  flex-wrap: wrap;\n"
    "  flex: 1;\n"
    "  justify-content: center;\n"
    "}\n"
    "\n"
    ".ring-wrap {\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  align-items: center;\n"
    "  gap: 10px;\n"
    "}\n"
    "\n"
    ".ring {\n"
    "  // --fill and --clr set via inline style binding\n"
    "  width: 118px;\n"
    "  height: 118px;\n"
    "  border-radius: 50%;\n"
    "  background: conic-gradient(var(--clr) 0% var(--fill), #dde5ef var(--fill) 100%);\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  justify-content: center;\n"
    "  flex-shrink: 0;\n"
    "  transition: transform 0.2s;\n"
    "\n"
    "  &:hover {\n"
    "    transform: scale(1.04);\n"
    "  }\n"
    "}\n"
    "\n"
    ".ring-inner {\n"
    "  width: 86px;\n"
    "  height: 86px;\n"
    "  border-radius: 50%;\n"
    "  background: var(--gov-surface);\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  align-items: center;\n"
    "  justify-content: center;\n"
    "}\n"
    "\n"
    ".ring-num {\n"
    "  font-size: 1.6rem;\n"
    "  font-weight: 800;\n"
    "  color: var(--gov-text);\n"
    "  line-height: 1;\n"
    "  font-family: 'Raleway', sans-serif;\n"
    "}\n"
    "\n"
    ".ring-label {\n"
    "  font-size: 0.72rem;\n"
    "  font-weight: 700;\n"
    "  color: var(--gov-text-muted);\n"
    "  text-transform: uppercase;\n"
    "  letter-spacing: 0.5px;\n"
    "  text-align: center;\n"
    "  max-width: 90px;\n"
    "}\n"
    "\n"
    "// ==========================================\n"
    "// MINI BAR CHART\n"
    "// ==========================================\n"
    ".mini-chart {\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  gap: 8px;\n"
    "  align-items: stretch;\n"
    "  min-width: 200px;\n"
    "  flex: 0 0 auto;\n"
    "}\n"
    "\n"
    ".mini-chart-bars {\n"
    "  display: flex;\n"
    "  align-items: flex-end;\n"
    "  gap: 10px;\n"
    "  height: 110px;\n"
    "}\n"
    "\n"
    ".mini-bar-col {\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  align-items: center;\n"
    "  gap: 3px;\n"
    "  flex: 1;\n"
    "}\n"
    "\n"
    ".mini-bar-value {\n"
    "  font-size: 0.7rem;\n"
    "  font-weight: 700;\n"
    "  color: var(--gov-text-secondary);\n"
    "  line-height: 1;\n"
    "}\n"
    "\n"
    ".mini-bar-track {\n"
    "  height: 88px;\n"
    "  width: 100%;\n"
    "  background: var(--gov-border);\n"
    "  border-radius: 6px;\n"
    "  display: flex;\n"
    "  align-items: flex-end;\n"
    "  overflow: hidden;\n"
    "}\n"
    "\n"
    ".mini-bar {\n"
    "  width: 100%;\n"
    "  border-radius: 6px 6px 0 0;\n"
    "  transition: height 0.6s ease;\n"
    "  min-height: 4px;\n"
    "}\n"
    "\n"
    ".mini-bar-lbl {\n"
    "  font-size: 0.65rem;\n"
    "  font-weight: 700;\n"
    "  color: var(--gov-text-muted);\n"
    "  text-transform: uppercase;\n"
    "  letter-spacing: 0.3px;\n"
    "}\n"
    "\n"
    ".mini-chart-footer {\n"
    "  font-size: 0.68rem;\n"
    "  font-weight: 700;\n"
    "  color: var(--gov-text-muted);\n"
    "  text-transform: uppercase;\n"
    "  letter-spacing: 0.5px;\n"
    "  text-align: center;\n"
    "  border: 1.5px solid var(--gov-border);\n"
    "  border-radius: 20px;\n"
    "  padding: 4px 12px;\n"
    "  width: max-content;\n"
    "  margin: 0 auto;\n"
    "}\n"
    "\n"
    "// ==========================================\n"
    "// CONTENT GRID\n"
    "// ==========================================\n"
    ".content-grid {\n"
    "  display: grid;\n"
    "  grid-template-columns: 1fr 1.5fr;\n"
    "  gap: 20px;\n"
    "  align-items: start;\n"
    "}\n"
    "\n"
    "// PANEL CARD\n"
    ".panel-card {\n"
    "  border-radius: 14px !important;\n"
    "  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05) !important;\n"
    "  border: 1px solid var(--gov-border) !important;\n"
    "\n"
    "  mat-card-header {\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: space-between;\n"
    "    padding: 16px 20px 10px;\n"
    "    gap: 12px;\n"
    "  }\n"
    "\n"
    "  mat-card-content {\n"
    "    padding: 0 20px 20px;\n"
    "  }\n"
    "}\n"
    "\n"
    ".panel-title {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  gap: 8px;\n"
    "  font-size: 0.92rem;\n"
    "  font-weight: 700;\n"
    "  color: var(--gov-text);\n"
    "  mat-icon { font-size: 18px; width: 18px; height: 18px; color: var(--gov-primary); }\n"
    "}\n"
    "\n"
    ".panel-link-btn {\n"
    "  flex-shrink: 0;\n"
    "  font-size: 0.78rem !important;\n"
    "  color: var(--gov-primary) !important;\n"
    "  border-color: var(--gov-border) !important;\n"
    "  border-radius: 8px !important;\n"
    "  height: 30px !important;\n"
    "  line-height: 28px !important;\n"
    "}\n"
    "\n"
    "// CATEGORY LIST\n"
    ".cat-list { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 13px; }\n"
    ".cat-row { display: flex; align-items: center; gap: 10px; }\n"
    "\n"
    ".cat-icon-wrap {\n"
    "  width: 34px; height: 34px; border-radius: 8px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  flex-shrink: 0;\n"
    "  mat-icon { font-size: 17px; width: 17px; height: 17px; }\n"
    "}\n"
    "\n"
    ".cat-info { flex: 1; min-width: 0; }\n"
    "\n"
    ".cat-meta {\n"
    "  display: flex; align-items: center; justify-content: space-between;\n"
    "  margin-bottom: 5px;\n"
    "}\n"
    "\n"
    ".cat-name {\n"
    "  font-size: 0.84rem; font-weight: 500; color: var(--gov-text);\n"
    "  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n"
    "}\n"
    "\n"
    ".cat-count {\n"
    "  display: flex; align-items: center; gap: 4px; flex-shrink: 0;\n"
    "  strong { font-size: 0.86rem; font-weight: 700; color: var(--gov-text); }\n"
    "}\n"
    "\n"
    ".cat-pct { font-size: 0.73rem; color: var(--gov-text-muted); }\n"
    "\n"
    ".cat-bar-track {\n"
    "  height: 5px; border-radius: 5px;\n"
    "  background: var(--gov-border); overflow: hidden;\n"
    "}\n"
    "\n"
    ".cat-bar-fill {\n"
    "  height: 100%; border-radius: 5px;\n"
    "  transition: width 0.6s ease; min-width: 4px;\n"
    "}\n"
    "\n"
    "// REPORTS TABLE\n"
    ".table-scroll { overflow-x: auto; }\n"
    "\n"
    ".reports-table {\n"
    "  width: 100%;\n"
    "\n"
    "  th {\n"
    "    font-size: 0.75rem; font-weight: 700;\n"
    "    color: var(--gov-text-secondary);\n"
    "    text-transform: uppercase; letter-spacing: 0.35px;\n"
    "    background: var(--gov-bg);\n"
    "  }\n"
    "\n"
    "  td {\n"
    "    font-size: 0.83rem; color: var(--gov-text);\n"
    "    padding: 9px 12px !important;\n"
    "    border-bottom: 1px solid var(--gov-border);\n"
    "    white-space: nowrap;\n"
    "  }\n"
    "}\n"
    "\n"
    ".clickable-row {\n"
    "  cursor: pointer; transition: background 0.12s;\n"
    "  &:hover td { background: var(--gov-bg); }\n"
    "  &:focus-visible { outline: 2px solid var(--gov-primary); outline-offset: -2px; }\n"
    "}\n"
    "\n"
    ".report-title-cell { display: flex; flex-direction: column; gap: 2px; max-width: 230px; }\n"
    ".report-title { font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n"
    ".report-citizen {\n"
    "  display: flex; align-items: center; gap: 2px;\n"
    "  font-size: 0.73rem; color: var(--gov-text-muted);\n"
    "  mat-icon { font-size: 11px; width: 11px; height: 11px; }\n"
    "}\n"
    "\n"
    ".category-cell { font-size: 0.8rem; color: var(--gov-text-secondary); }\n"
    ".date-cell { font-size: 0.78rem; color: var(--gov-text-muted); }\n"
    "\n"
    "// STATUS CHIP\n"
    ".status-chip {\n"
    "  display: inline-block;\n"
    "  padding: 3px 9px;\n"
    "  border-radius: 20px;\n"
    "  font-size: 0.72rem;\n"
    "  font-weight: 700;\n"
    "  text-transform: uppercase;\n"
    "  letter-spacing: 0.3px;\n"
    "\n"
    "  &[data-status='PENDING']     { background: var(--status-pending-bg);   color: var(--status-pending-text); }\n"
    "  &[data-status='IN_PROGRESS'] { background: #eff6ff;                    color: #1d4ed8; }\n"
    "  &[data-status='RESOLVED']    { background: var(--status-resolved-bg);  color: var(--status-resolved-text); }\n"
    "  &[data-status='REJECTED']    { background: var(--status-rejected-bg);  color: var(--status-rejected-text); }\n"
    "}\n"
    "\n"
    "// EMPTY STATE\n"
    ".empty-panel {\n"
    "  display: flex; flex-direction: column; align-items: center;\n"
    "  gap: 8px; padding: 32px 16px; color: var(--gov-text-muted);\n"
    "  mat-icon { font-size: 34px; width: 34px; height: 34px; opacity: 0.4; }\n"
    "  p { font-size: 0.86rem; margin: 0; }\n"
    "}\n"
    "\n"
    "// ==========================================\n"
    "// RESPONSIVE\n"
    "// ==========================================\n"
    "@media (max-width: 1100px) {\n"
    "  .overview-body { flex-direction: column; align-items: stretch; }\n"
    "  .overview-vdivider { width: 100%; height: 1px; margin: 0 0 20px; }\n"
    "  .mini-chart { min-width: unset; }\n"
    "  .mini-chart-bars { height: 80px; }\n"
    "  .mini-bar-track { height: 64px; }\n"
    "  .content-grid { grid-template-columns: 1fr; }\n"
    "}\n"
    "\n"
    "@media (max-width: 640px) {\n"
    "  .welcome-hero { padding: 16px; flex-direction: column; align-items: flex-start; }\n"
    "  .manage-btn { width: 100%; justify-content: center; }\n"
    "  .rings-area { gap: 16px; }\n"
    "  .ring { width: 96px; height: 96px; }\n"
    "  .ring-inner { width: 68px; height: 68px; }\n"
    "  .ring-num { font-size: 1.25rem; }\n"
    "  .overview-body { padding: 20px 16px; }\n"
    "  .overview-footer { padding: 10px 16px; }\n"
    "}\n"
)

path_scss = r"c:\Users\jose\Desktop\PROYECTOS GIT\Echarati-road-reports\src\app\features\admin\pages\dashboard\dashboard-page.component.scss"
with open(path_scss, "w", encoding="utf-8") as f:
    f.write(scss)
print("dashboard SCSS OK")
